### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by donovanhiland** [mmazzarolo/eslint-plugin-react-app#1]
warning "eslint-plugin-react-app > eslint-config-react-app@2.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".

when running
```
yarn add --dev eslint@^4.1.1 eslint-plugin-react-app
```

I get the above warning. I also have to specify the eslint version because it doesn't look like the latest eslint version 5 is supported.

Any ideas? I can't see where this peer dependency is coming from. It's not specified in the eslint-config-react-app package.json as needing that version.

**Comment by dagadbm** [comment]
hey,

i have the same problem as well.

but it is shown in the package.json of this project here:

```
  "peerDependencies": {
    "eslint": "^4.1.1"
  },
```

**Comment by mmazzarolo** [comment]
Hey @donovanhiland and @dagadbm , sorry, for some reasons the "watch" option on this repo was disabled 😢 
Are you still having the issue?
it is working fine for me (I'm using it in a few react and react-native pj).

Example package.json:
```
    "eslint": "^5.3.0",
    "eslint-plugin-react-app": "^3.0.0",
```
