### ISSUE TITLE
Some fundamental knowledge about the recommended config

### ISSUE THREAD

**Issue by ZYinMD** [mmazzarolo/eslint-plugin-react-app#15]
Hi, I hope to ask some basic questions to understand the recommended rule set (`plugin:react-app/recommended`) of this package :

1. In a non-CRA project, if I install \`eslint-**config**-react-app\`, plus manually install **all** the plugins, will I get mostly identical rules as from this package ? In other words:
```js
"extends": [
  "react-app", // same as ↓ if I install all the plugins?
  "plugin:react-app/recommended"
]
```

2. In a CRA project where env var `EXTEND_ESLINT=true` is set,  is 1 still true, with the only difference being that I don't need to manually install any plugins?

3. Some plugins have their own "recommended" configs, are they most the same as in the CRA config?  In other words:
```js
"extends": [
  "plugin:react-app/recommended",
  "plugin:react/recommended", // same as covered above ↑ ?
  "plugin:react-hooks/recommended", // same as covered above ↑ ?
  "plugin:@typescript-eslint/recommended" // same as covered above ↑ ? (I guess this one may be not)
]
```

4. Does this config use the `@typescript-eslint/parser`?
```js
{
  "parser": "@typescript-eslint/parser"
}
```
If yes, what if I write `js` instead of `ts`? My assumption is that this parser is totally capable of parsing `js` too, but I'm not sure.

5. CRA includes `jest` out of the box, but it seems neither CRA nor this plugin includes `eslint-plugin-jest`, correct? Therefore if I want to lint my tests, I should manually install the jest plugin and extend `plugin:jest/recommended` myself, no matter if I use CRA of this plugin, correct?

Thanks so much for your time!!

**Comment by mmazzarolo** [comment]
Hey @ZYinMD !

> 1. In a non-CRA project, if I install `eslint-config-react-app`, plus manually install all the plugins, will I get mostly identical rules as from this package ?

Yep!

> 2. In a CRA project where env var EXTEND_ESLINT=true is set, is 1 still true, with the only difference being that I don't need to manually install any plugins?

For the same reason above, I wouldn't use `eslint-plugin-react-app` in a CRA project. But maybe I'm missing your point? 🤔 

> 3. Some plugins have their own "recommended" configs, are they most the same as in the CRA config? In other words:

Yes, `eslint-plugin-react-app` is importing and using the `eslint-config-react-app` config ([here](https://github.com/mmazzarolo/eslint-plugin-react-app/blob/master/src/config.js)), so you should expect the same behaviours.

> 4. Does this config use the @typescript-eslint/parser?

Yes.

> If yes, what if I write js instead of ts? My assumption is that this parser is totally capable of parsing js too, but I'm not sure.

Correct. See [`react-native-modal-datetime-picker` as a pure JS example](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/package.json#L43-L46). 

> 5. CRA includes jest out of the box, but it seems neither CRA nor this plugin includes eslint-plugin-jest, correct? Therefore if I want to lint my tests, I should manually install the jest plugin and extend plugin:jest/recommended myself, no matter if I use CRA of this plugin, correct?

Correct. In all honesty I never use the `eslint-plugin-jest`. I just set the test environment to `jest`. ESLint supports out of the box:

```js
// .eslintrc
"overrides": [
    {
      "files": [
        "**/**/*.test.js"
      ],
      "env": {
        "jest": true
      }
    }
  ]
```

Let me know if it makes sense 👍

**Comment by ZYinMD** [comment]
Thanks very much!

About point 2, why I use `eslint-config-react-app` when in a CRA project: It's my understanding that if I want to set my own `eslintrc.json` in a CRA project, I'll need to to set `EXTEND_ESLINT=true`, which will disable the default eslint setup of CRA. Then I'll need to extend `eslint-config-react-app` myself. 
```js
extends: ["react-app"]
```
This is documented [here](https://create-react-app.dev/docs/setting-up-your-editor/#experimental-extending-the-eslint-config).

About point 3, today I checked the source code (surprisingly easy to), and found that the "recommended" configs of other plugins are more strict than CRA, so I end up extending them anyways:
```js
extends: [
  "plugin:@typescript-eslint/recommended", // this is stricter than CRA
  "plugin:react/recommended", // this is stricter than CRA
  "plugin:react-app/recommended" // less strict, but turns off 2-3 rules enabled above, so extends it last
]

```
