### ISSUE TITLE
Upgrade to babel-eslint 10

### ISSUE THREAD

**Issue by trollepierre** [mmazzarolo/eslint-plugin-react-app#3]
I got this issue:
` eslint-config-react-app@3.0.8" has incorrect peer dependency "babel-eslint@9.x".`

I believe we can upgrade eslint plugin react app to babel-eslint 10

**Comment by mmazzarolo** [comment]
Hey! Mind trying `eslint-plugin-react-app@5.0.0-beta.1`?

**Comment by mmazzarolo** [comment]
@trollepierre was it working?

**Comment by trollepierre** [comment]
actually I realized that my project is not using the repository but another one. I didn't try :p
