### ISSUE TITLE
Property "overrides" in the wrong type

### ISSUE THREAD

**Issue by visualcookie** [mmazzarolo/eslint-plugin-react-app#4]
Hi.

Somehow I'm getting errors from ESLint.

Error message:
![image](https://user-images.githubusercontent.com/1857554/60269522-e4d03700-98ee-11e9-9dd1-6ca367f9529c.png)

`.eslintrc.js`
```
module.exports = {
  globals: {
    __PATH_PREFIX__: true,
  },
  extends: [
    "react-app",
    "airbnb",
    "prettier",
    "prettier/react",
    "prettier/flowtype",
  ],
  plugins: ["prettier", "flowtype"],
}
```

**Comment by mmazzarolo** [comment]
@visualcookie you should [extend `plugin:react-app/recommended`](https://github.com/mmazzarolo/eslint-plugin-react-app#setup)

**Comment by visualcookie** [comment]
Okay, then the Gatsby doc got confused, but this doesn't work aswell. Results in the following error:
```
[Error - 4:35:31 PM] 
Failed to load plugin 'react-app' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-react-app'

This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-react-app' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-react-app' isn't installed correctly.
```

**Comment by visualcookie** [comment]
Ah wait, sorry. I somehow mixed up my package stack. I got a package installed that almost had the same name as yours.

`eslint-config-react-app`

Closed.
